### ISSUE TITLE
Create MAtch making ticket

### ISSUE THREAD

**Issue by ashishlijhara** [PlayFab/UnrealMarketplacePlugin#18]
​I see a crash at the Create Matchmaking ticket in Unreal. The graph for blueprint section that handles this is below:
![Capture](https://user-images.githubusercontent.com/292193/79071598-3a4cc780-7cfa-11ea-9a7d-257d17f1d504.PNG)

The log is below:

UE4Editor_PlayFab!UPlayFabMultiplayerAPI::execCreateMatchmakingTicket() [c:\users\user\downloads\emptytrial\plugins\playfab\source\playfab\classes\playfabmultiplayerapi.h:29] UE4Editor_CoreUObject UE4Editor_CoreUObject UE4Editor_CoreUObject UE4Editor_CoreUObject UE4Editor_CoreUObject UE4Editor_CoreUObject UE4Editor_CoreUObject UE4Editor_CoreUObject UE4Editor_CoreUObject UE4Editor_Engine UE4Editor_PlayFab!UPlayFabMultiplayerAPI::FDelegateOnSuccessRequestMultiplayerServer_DelegateWrapper() [c:\users\user\downloads\emptytrial\plugins\playfab\source\playfab\classes\playfabmultiplayerapi.h:694] UE4Editor_PlayFab!UPlayFabMultiplayerAPI::HelperRequestMultiplayerServer() [c:\users\user\downloads\emptytrial\plugins\playfab\source\playfab\private\playfabmultiplayerapi.cpp:2811] UE4Editor_PlayFab!UPlayFabMultiplayerAPI::execHelperRequestMultiplayerServer() [c:\users\user\downloads\emptytrial\plugins\playfab\source\playfab\classes\playfabmultiplayerapi.h:29] UE4Editor_CoreUObject UE4Editor_CoreUObject UE4Editor_PlayFab!TMulticastScriptDelegate<FWeakObjectPtr>::ProcessMulticastDelegate<UObject>() [c:\unrealinstalls\ue_4.24\engine\source\runtime\core\public\uobject\scriptdelegates.h:488] UE4Editor_PlayFab!FOnPlayFabMultiplayerRequestCompleted::Broadcast() [c:\users\user\downloads\emptytrial\plugins\playfab\source\playfab\classes\playfabmultiplayerapi.h:24] UE4Editor_PlayFab!UPlayFabMultiplayerAPI::OnProcessRequestComplete() [c:\users\user\downloads\emptytrial\plugins\playfab\source\playfab\private\playfabmultiplayerapi.cpp:3278] UE4Editor_PlayFab!TBaseUObjectMethodDelegateInstance<0,UPlayFabMultiplayerAPI,void __cdecl(TSharedPtr<IHttpRequest,0>,TSharedPtr<IHttpResponse,1>,bool)>::ExecuteIfSafe() [c:\unrealinstalls\ue_4.24\engine\source\runtime\core\public\delegates\delegateinstancesimpl.h:709] UE4Editor_HTTP UE4Editor_HTTP UE4Editor_HTTP UE4Editor_Core UE4Editor_Core UE4Editor_Core UE4Editor_Core UE4Editor UE4Editor UE4Editor UE4Editor UE4Editor kernel32 ntdll

Since I wanted to Double Check, I used Post man to check the above logic. Turns out, it is correct.

I would really appreciate any pointers. Thanks

**Comment by pgilmorepf** [comment]
Thanks for notifying us. We will investigate.

**Comment by ashishlijhara** [comment]
FYI, the crash occurs both in the UE version compiled from source and the installed version. I also did not enable the FORCE_THREADSAFE_SHAREDPTRS in SharedPointerInternals.h yet. You reckon this could make a difference?

**Comment by ashishlijhara** [comment]
Just for reference, here is the screenshot from the postman request
![Capture](https://user-images.githubusercontent.com/292193/79257735-afa9cb00-7ea7-11ea-95f2-318ff77c989f.PNG)

**Comment by ashishlijhara** [comment]
Now as an update, since I was passing an empty array, thus the blueprint was crashing. But as you can clearly see here that should not have been the case if an empty array is passed int MembersToMatchWith.

**Comment by toddbellMSFT** [comment]
Hello @ashishlijhara can you provide us with an example project? Your blueprint image does not give enough info for us to repro your noted crash.

**Comment by ashishlijhara** [comment]
Hi, I was able to fix the issue by removing any pins from the make array node. I hope that helps anyone else. Thanks.
