### ISSUE TITLE
LogCompile: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.

### ISSUE THREAD

**Issue by k1p1** [PlayFab/UnrealMarketplacePlugin#7]
https://github.com/PlayFab/UnrealMarketplacePlugin/blob/22947a0b9d8d88a2daeaddbe9570c6975f2159d4/4.21/PlayFabPlugin/PlayFab/Source/PlayFabCommon/Public/PlayFabAuthenticationContext.h#L147

You will need a full rebuild to reproduce issue.

LogCompile: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.

Solution: Replace this line with:
`UFUNCTION(BlueprintCallable, Category = "PlayFab | Core")`

**Comment by pgilmorepf** [comment]
https://github.com/PlayFab/SDKGenerator/pull/468
